name: OpenSearch Dashboards Build Custom Docker Image

on:
  workflow_dispatch:

jobs:
  Build-Custom-Docker-Image:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: append content
        env:
          TRACKING_ID: ${{secrets.GA_TRACKING_ID}}
          PLUGINS: ${{secrets.PLUGINS}}
        run: |
          if [[ $TRACKING_ID ]]; then
            echo -e "\r\n" >> config/playground/docker/dev/extra_config/osd.yml
            echo google_analytics_plugin.trackingID: $TRACKING_ID >> config/playground/docker/dev/extra_config/osd.yml
          fi
          echo -e "\r\n" >> config/playground/docker/dev/Dockerfile
          echo CMD [\"python\", \"/opt/opensearch-dashboards/scripts/custom_osd_entry.py\", \"$PLUGINS\"] >> config/playground/docker/dev/Dockerfile

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        run:  |
          chmod -R 777 config/playground/docker/dev/scripts/
          docker build -t joycelulu/opensearch-dashboards:2.3.1 config/playground/docker/dev
          docker push joycelulu/opensearch-dashboards:2.3.1

