name: OpenSearch Dashboards Build Custom Docker Image

on:
  workflow_dispatch:

jobs:
  Build-Custom-Docker-Image:
    runs-on: ubuntu-latest
    uses: BionIT/dashboards-anywhere/.github/workflows/test-null.yml@test
    secrets:
      ga-tracking-id: ${{ secrets.GA_TRACKING_ID }}
